### ISSUE TITLE
Replace logging by System.out.println with SLF4J Logger 

### ISSUE THREAD

**Issue by mdolata** [mdolata/TicTacToe#4]
As in title. There is multiple occurences of SysOut. It looks terrible so I'd like to replace it with proper logger.

**Comment by priyankalakhe** [comment]
@mdolata  - I can take a look at this issue. 

Here's the occurrences I can take a look at and update to using the `SL4J` logger. 

https://github.com/mdolata/TicTacToe/search?q=system.out&unscoped_q=system.out

Let me know if this is ok and I can send out a PR.

**Comment by sushangagneja** [comment]
Can work on this!

**Comment by notepad104** [comment]
Slf4j is just a logging facade, abstraction layer over the logging component. You should use Slf4j_over_log4j implemenation which has log4j as a logging component with abstaction functionalities of Slf4j.

**Comment by mdolata** [comment]
@priyankalakhe yes, that'd be great, please read @notepad104 comment and try your best. I'm going to assign this issue to you.

@sushangagneja too late, but you can subscribe this issue in case it will be abandoned. You are the second in the queue.

@notepad104 thanks for your comment.

**Comment by mdolata** [comment]
done by @priyankalakhe in #9
